### ISSUE TITLE
psr-2方法名命名规则

### ISSUE THREAD

**Issue by lichunqiang** [hfcorriez/fig-standards#12]
> 方法名则必须使用camelCase()风格来声明。

在psr-1中指出方法名使用驼峰命名，那么完全满足psr-2的话，方法名也许遵守psr-1中的驼峰命名吗？还是定义成 `foo_bar()` 也可以。

**Comment by thbourlove** [comment]
@lichunqiang 
PSR-2第一条规则就是必须首先满足PSR-1。所以必须使用camelCase，foo_bar是不符合规范的。

**Comment by lichunqiang** [comment]
@thbourlove okay, thanks!
