### ISSUE TITLE
PSR-4出来了

### ISSUE THREAD

**Issue by weakish** [hfcorriez/fig-standards#5]
如题

**Comment by thbourlove** [comment]
@weakish 你可以考虑翻译一下，提个pull request嘛。

**Comment by hfcorriez** [comment]
多谢提醒，最近事多，暂时没空。 @thbourlove 说的不错 可以一起来写

**Comment by 872409** [comment]
@hfcorriez 
PSR-4  3. 范例中 第一个例子: **实际的类文件路径:** `./acme-log-writer/lib/File_Writer.php` 这个是不是错了?根据:
- 每一个在类名中的 `_` 符号都会被转化成 `DIRECTORY_SEPARATOR`

应该是 `./acme-log-writer/lib/File/Writer.php` 而不是 `./acme-log-writer/lib/File_Writer.php`,不知道在下理解的对否?

| 完整的类名 | 命名空间前缀 | 基础目录 | 实际的类文件路径 |
| --- | --- | --- | --- |
| \Acme\Log\Writer\File_Writer | Acme\Log\Writer | ./acme-log-writer/lib/ | ./acme-log-writer/lib/File_Writer.php `应该是:` `./acme-log-writer/lib/File/Writer.php` |

**Comment by thbourlove** [comment]
@xuxiao 
非常抱歉，是翻译出了问题。psr4里下划线`_`在类名中是没有任何特殊意义的。所以例子没错。
每一个在类名中的 _ 符号都会被转化成 DIRECTORY_SEPARATOR。是psr0的规范。翻译的人估计不小心复制粘贴了psr0的规范过来。

**Comment by hfcorriez** [comment]
@thbourlove @xuxiao  刚看到确实如此，没有仔细核对。

**Comment by 872409** [comment]
@thbourlove @hfcorriez 
嗯,刚看了一下 https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md 
确实翻译错了:
- Underscores have no special meaning in any portion of the fully qualified class name.

感谢你们的付出和努力![100个赞]

**Comment by hfcorriez** [comment]
see #8

**Comment by hfcorriez** [comment]
如果有空，请一起来 review！

**Comment by hfcorriez** [comment]
已经对翻译进行了校对和优化，感谢各位的热心和努力！ @xuxiao @thbourlove
